# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "."
destination:    ./_site
host:           0.0.0.0
port:           9001
baseurl:        ""
url:            "https://marcosm3.com"
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - assets/scss/
  - build/
  - node_modules/
  - scss/
  - CODE_OF_CONDUCT.md
  - Gemfile
  - Gemfile.lock
  - package.js
  - package.json
  - package-lock.json
  - README.md
  - sache.json

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Social
title:              Marcos M3
description:        "Marcos y Molduras"
authors:            "Benjamín Camacho"

toc:
  min_level:        2
  max_level:        4


google_analytics: UA-1302093099-2
